name: Run tests

on: [ push, pull_request ]

jobs:
  integration-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and run the Docker compose topology
        run: |
          sh ./build-image.sh
          sh ./run-compose.sh &

      - name: Run Cucumber tests
        run: |
          python3 .github/scripts/wait_online.py
          cd gamify-specs/
          mvn clean test

      - name: Upload report as GitHub artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@master
        with:
          name: report
          path: gamify-specs/target/cucumber

      - name: Upload report to GitHub pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          mkdir report
          cp gamify-specs/target/cucumber report/index.html
          cd report
          git init .
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git add .
          git commit -m "Deployed 🚀"
          git remote add origin https://${{secrets.TOKEN_GITHUB}}@github.com/${{github.repository}}.git
          git checkout -b gh-pages
          git push -u origin gh-pages --force
